### ISSUE TITLE
Plugin crash in debian jessie xbmc gothan

### ISSUE THREAD

**Issue by susobaco** [enen92/P2P-Streams-Kodi#80]
The log:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PROTOCOL_SSLv3'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/plugin.video.p2p-streams/default.py", line 14, in <module>
                                                from resources.core import sopcast as sop
                                              File "/home/xbmc/.xbmc/addons/plugin.video.p2p-streams/resources/core/sopcast.py", line 11, in <module>
                                                import xbmc,xbmcgui,xbmcplugin,urllib2,os,sys,subprocess,xbmcvfs,socket,re,requests,shutil
                                              File "/home/xbmc/.xbmc/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/xbmc/.xbmc/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
                                                ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
                                            AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
                                            -->End of Python script error report<--

**Comment by enen92** [comment]
https://github.com/enen92/P2P-Streams-Kodi/issues/70

**Comment by susobaco** [comment]
https://github.com/beenje/script.module.requests/issues/5
