### ISSUE TITLE
p2p streams error

### ISSUE THREAD

**Issue by spektus** [enen92/P2P-Streams-Kodi#92]
Please have a look whats wrong with it.

 
01:20:29 T:1786727696  NOTICE: GL_VENDOR = ARM
01:20:29 T:1786727696  NOTICE: GL_RENDERER = Mali-450 MP
01:20:29 T:1786727696  NOTICE: GL_VERSION = OpenGL ES 2.0
01:20:29 T:1786727696  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
01:20:29 T:1786727696  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil
01:20:30 T:1865060672  NOTICE: Thread JobWorker start, auto delete: true
01:20:32 T:1920509392  NOTICE: Thread LanguageInvoker start, auto delete: false
01:20:32 T:1920509392  NOTICE: -->Python Interpreter Initialized<--
01:20:35 T:1920509392  NOTICE: Mode: 401
01:20:35 T:1920509392  NOTICE: URL: https://code.google.com/p/p2p-strm/
01:20:35 T:1920509392  NOTICE: Name: 1Torrent.tv
01:20:35 T:1920509392  NOTICE: Iconimage: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.p2p-streams/resources/core/parsers/onetorrenttv/icon.png
01:20:35 T:1920509392  NOTICE: Parser: onetorrenttv
01:20:35 T:1920509392  NOTICE: Parserfunction: None
01:20:35 T:1920509392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.p2p-streams/default.py", line 157, in <module>
                                                parser_module.module_tree(name,url,iconimage,mode,parser,parserfunction)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.p2p-streams/resources/core/parsers/onetorrenttv/main.py", line 22, in module_tree
                                                if not parserfunction: onetorrent_main()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.p2p-streams/resources/core/parsers/onetorrenttv/main.py", line 26, in onetorrent_main
                                                html_source = clean(get_page_source(base_url+"/channels.php"))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.p2p-streams/resources/core/peertopeerutils/webutils.py", line 62, in get_page_source
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 391, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 409, in _open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1161, in http_open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1136, in do_open
                                            URLError: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
                                            -->End of Python script error report<--
01:20:36 T:1786727696   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.p2p-streams/?iconimage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.p2p-streams%2fresources%2fcore%2fparsers%2fonetorrenttv%2ficon.png&mode=401&name=1Torrent.tv&parser=onetorrenttv&url=https%3a%2f%2fcode.google.com%2fp%2fp2p-strm%2f
01:20:36 T:1786727696   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.p2p-streams/?iconimage=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.p2p-streams%2fresources%2fcore%2fparsers%2fonetorrenttv%2ficon.png&mode=401&name=1Torrent.tv&parser=onetorrenttv&url=https%3a%2f%2fcode.google.com%2fp%2fp2p-strm%2f) failed
01:20:36 T:1856241672  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by enen92** [comment]
No parser help.
