### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eN0Rm** [enen92/P2P-Streams-Kodi#93]
```
15:43:47 T:139672972543744  NOTICE: Module is up to date: arenavision
15:43:49 T:139672972543744  NOTICE: Module is up to date: livefootballws
15:43:58 T:139672972543744  NOTICE: Module is up to date: livefootballvideo
15:43:59 T:139672972543744  NOTICE: Module is up to date: torrenttvruall
15:44:00 T:139672972543744  NOTICE: Module is up to date: rojadirecta
15:44:01 T:139672972543744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('url',)
                                            Traceback (most recent call last):
                                              File "/home/fn/.kodi/addons/plugin.video.p2p-streams/default.py", line 151, in <module>
                                                elif mode==400: parsers.addon_parsers_menu()
                                              File "/home/fn/.kodi/addons/plugin.video.p2p-streams/resources/core/parsers/parsers.py", line 88, in addon_parsers_menu
                                                sync_parser()
                                              File "/home/fn/.kodi/addons/plugin.video.p2p-streams/resources/core/parsers/parsers.py", line 227, in sync_parser
                                                module_url = text['url']
                                            KeyError: ('url',)
                                            -->End of Python script error report<--
15:44:01 T:139674792925120   ERROR: GetDirectory - Error getting plugin://plugin.video.p2p-streams/?iconimage=%2fhome%2ffn%2f.kodi%2faddons%2fplugin.video.p2p-streams%2fresources%2fart%2fweb-parsers-menu.png&mode=400&name=-Addon%20Website-parsers&url=https%3a%2f%2fcode.google.com%2fp%2fp2p-strm%2f
15:44:01 T:139674792925120   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.p2p-streams/?iconimage=%2fhome%2ffn%2f.kodi%2faddons%2fplugin.video.p2p-streams%2fresources%2fart%2fweb-parsers-menu.png&mode=400&name=-Addon%20Website-parsers&url=https%3a%2f%2fcode.google.com%2fp%2fp2p-strm%2f) failed
15:44:01 T:139672972543744  NOTICE: Thread BackgroundLoader start, auto delete: false
15:44:01 T:139672963102464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.p2p-streams/?url=https%3A%2F%2Fcode.google.com%2Fp%2Fp2p-strm%2F&mode=4&name=%5BCOLOR+orange%5DAceStream%3A+%5B%2FCOLOR%5DPlay+Acestream+hash+%2F+Torrent+URL&iconimage=%2Fhome%2Ffn%2F.kodi%2Faddons%2Fplugin.video.p2p-streams%2Fresources%2Fart%2Facestream-menu-item.png
15:44:01 T:139672963102464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.p2p-streams/?url=https%3A%2F%2Fcode.google.com%2Fp%2Fp2p-strm%2F&mode=3&name=%5BCOLOR+orange%5DSopCast%3A+%5B%2FCOLOR%5DPlay+SopCast+ID&iconimage=%2Fhome%2Ffn%2F.kodi%2Faddons%2Fplugin.video.p2p-streams%2Fresources%2Fart%2Fsopcast-menu-item.png
15:44:01 T:139672963102464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.p2p-streams/?url=https%3A%2F%2Fcode.google.com%2Fp%2Fp2p-strm%2F&mode=5&name=%5BCOLOR+orange%5DSopCast%3A+%5B%2FCOLOR%5DPlay+SopCast+URL&iconimage=%2Fhome%2Ffn%2F.kodi%2Faddons%2Fplugin.video.p2p-streams%2Fresources%2Fart%2Fsopcast-menu-item.png
15:44:01 T:139672595982080 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.p2p-streams/?url=https%3A%2F%2Fcode.google.com%2Fp%2Fp2p-strm%2F&mode=6&name=%5BCOLOR+orange%5DAceStream%3A+%5B%2FCOLOR%5DLoad+local+.torrent+file&iconimage=%2Fhome%2Ffn%2F.kodi%2Faddons%2Fplugin.video.p2p-streams%2Fresources%2Fart%2Facestream-menu-item.png
(END)
```

ubuntu 15.04 ppa

**Comment by enen92** [comment]
Probably the url you're syncing the parsers from have changed or a single parser was removed from the source. That's not something that belongs to the addon though, hence issue closed.
